name       : galculator
version    : 2.1.4
release    : 4
source     :
    - https://github.com/galculator/galculator/archive/v2.1.4.tar.gz : dcbdb48ddf8a3f68b9aa5902f880f174fd269de2b7410988148d05871012e142
license    : GPL-2.0
component  : office.maths
summary    : GTK2 / GTK3 based calculator
description: |
    galculator is a calculator based on GTK2 / GTK3 that is capable of ordinary notation as well as reverse polish notation (RPN), formula entry mode, different number bases, and angles.
builddeps  :
    - pkgconfig(atk-bridge-2.0)
    - pkgconfig(freetype2)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(harfbuzz)
    - pkgconfig(libpng)
    - pkgconfig(pango)
    - pkgconfig(pixman-1)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
