name        : galculator
version     : 2.1.3
release     : 1
source     :
    - http://internode.dl.sourceforge.net/project/galculator/galculator/2.1.3/galculator-2.1.3.tar.bz2 : 91ac62d6d74da910cb79c68f7bf3f4505ac0efe51091150c4ea54fe1c1306235
license     : GPL-2.0
summary     : GTK2 / GTK3 based calculator
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(atk-bridge-2.0)
    - pkgconfig(harfbuzz)
    - pkgconfig(pango)
    - pkgconfig(freetype2)
    - pkgconfig(libpng)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(pixman-1)
    - pkgconfig(glib-2.0)
description : |
    galculator is a calculator based on GTK2 / GTK3 that is capable of ordinary notation as well as reverse polish notation (RPN), formula entry mode, different number bases, and angles.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
